#!/bin/sh
#
#  Install
###########################################################################
#
#  Purpose:  This script invokes the Ant utility to perform the build for
#            this product.
#
#  Usage:  Install
#
###########################################################################

mvn -Dmaven.repo.local=${MAVEN_REPO_LOCAL} clean package install
